-- DO NOT DO DROPS HERE!!!

CREATE TABLE IF NOT EXISTS urls (
  id VARCHAR(6) PRIMARY KEY,
  url VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS metadata (
  id VARCHAR(6) REFERENCES urls(id),
  url VARCHAR NOT NULL,
  hits INT NOT NULL
);
